import { authTables } from "@convex-dev/auth/server";
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  ...authTables,
  members: defineTable({
    externalId: v.string(),
    name: v.string(),
    email: v.string(),
    password_hash: v.union(v.string(), v.null()),
    failedLoginAttempts: v.union(v.number(), v.null()),
    lockedUntil: v.union(v.string(), v.null()),
    staffId: v.union(v.string(), v.null()),
    role: v.union(v.literal("member"), v.literal("loan_officer"), v.literal("admin"), v.literal("treasurer")),
    status: v.union(v.literal("active"), v.literal("on_hold"), v.literal("inactive")),
    savings_balance: v.number(),
    voluntary_savings: v.number(),
    monthly_savings: v.number(),
    interest_earned_ytd: v.number(),
    mandatory_target: v.number(),
    mandatory_actual: v.number(),
  }).index("by_externalId", ["externalId"]).index("by_email", ["email"]).index("by_role", ["role"]),
  products: defineTable({
    externalId: v.string(),
    name: v.string(),
    description: v.string(),
    category: v.string(),
    price: v.number(),
    stock_quantity: v.number(),
    is_active: v.boolean(),
    image_url: v.string(),
  }).index("by_externalId", ["externalId"]).index("by_category", ["category"]),
  loans: defineTable({
    externalId: v.string(),
    memberExternalId: v.string(),
    member_name: v.string(),
    member_email: v.string(),
    productExternalId: v.string(),
    product_name: v.string(),
    product_image_url: v.string(),
    total_loan_amount: v.number(),
    total_repayment_amount: v.number(),
    monthly_installment: v.number(),
    repayment_duration_months: v.number(),
    interest_rate: v.number(),
    purpose: v.string(),
    status: v.union(v.literal("pending"), v.literal("active"), v.literal("rejected"), v.literal("cleared")),
    amount_paid: v.number(),
    created_at: v.string(),
    approved_by: v.union(v.string(), v.null()),
    approved_at: v.union(v.string(), v.null()),
    next_emi_date: v.union(v.string(), v.null()),
  }).index("by_externalId", ["externalId"]).index("by_memberExternalId", ["memberExternalId"]),
  transactions: defineTable({
    externalId: v.string(),
    memberExternalId: v.string(),
    title: v.string(),
    type: v.union(v.literal("deposit"), v.literal("loan_repayment"), v.literal("interest_credit")),
    amount: v.number(),
    date: v.string(),
    reference: v.string(),
  }).index("by_memberExternalId", ["memberExternalId"]),
  contributions: defineTable({
    externalId: v.string(),
    memberExternalId: v.string(),
    amount: v.number(),
    type: v.union(v.literal("mandatory"), v.literal("voluntary")),
    date: v.string(),
  }).index("by_memberExternalId", ["memberExternalId"]),
  settings: defineTable({
    externalId: v.string(),
    mandatory_savings_amount: v.number(),
    savings_interest_rate: v.number(),
    loan_interest_rate: v.number(),
    max_loan_multiplier: v.number(),
    max_repayment_months: v.number(),
  }).index("by_externalId", ["externalId"]),
  applications: defineTable({
    externalId: v.string(),
    name: v.string(),
    email: v.string(),
    staff_id: v.string(),
    department: v.string(),
    phone: v.string(),
    monthly_savings: v.number(),
    status: v.union(v.literal("pending"), v.literal("approved"), v.literal("rejected")),
    submitted_at: v.string(),
  }).index("by_status", ["status"]),
  broadcasts: defineTable({
    externalId: v.string(),
    title: v.string(),
    body: v.string(),
    audience: v.string(),
    sent_at: v.string(),
    sent_by: v.string(),
  }).index("by_sent_at", ["sent_at"]),
  auditLogs: defineTable({
    externalId: v.string(),
    time: v.string(),
    user: v.string(),
    action: v.string(),
    ip: v.string(),
    level: v.union(v.literal("info"), v.literal("warning"), v.literal("danger")),
  }).index("by_time", ["time"]),
  monthlyDisbursements: defineTable({
    externalId: v.string(),
    month: v.string(),
    disbursed: v.number(),
    repaid: v.number(),
  }).index("by_month", ["month"]),
  sessions: defineTable({
    externalId: v.string(),
    token: v.string(),
    memberExternalId: v.string(),
    expiresAt: v.string(),
  }).index("by_token", ["token"]),
  password_resets: defineTable({
    externalId: v.string(),
    token: v.string(),
    memberExternalId: v.string(),
    expiresAt: v.string(),
  }).index("by_token", ["token"]),
});
